# Visualize Board Transformations

> Joseph P. Vantassel, The University of Texas at Austin

To cut down on the computational expense of training the tic-tac-toe model, we can utlize the inherent symetry present in the
game board.

Below is a single game state shown in eight possible unique ways. These eight possible combinations correspond to the eight
values the `trans_number` variable can assume.

In [2]:
import numpy as np

## Possibility #0

Base state (i.e., no manipulation).

In [3]:
state = np.array([[1,2,0],[2,0,1],[2,2,2]])
print(state)

[[1 2 0]
 [2 0 1]
 [2 2 2]]


## Possibility #1

Rotate 90 degrees clock-wise.

In [16]:
print(np.flip(np.transpose(state), 1))

[[2 2 1]
 [2 0 2]
 [2 1 0]]


## Possibility #2

Flip across diagnol spanning from lower-left to upper-right.

In [17]:
print(np.flip(np.flip(np.transpose(state), 1), 0))

[[2 1 0]
 [2 0 2]
 [2 2 1]]


## Possibility #3

Flip across diagnol spanning from upper-left to lower-right.

In [18]:
print(np.transpose(state))

[[1 2 2]
 [2 0 2]
 [0 1 2]]


## Possibility #4

Rotate 180 degrees clock-wise.

In [19]:
print(np.flip(np.flip(state, 0), 1))

[[2 2 2]
 [1 0 2]
 [0 2 1]]


## Possibility #5

Flip board across central vertical line.

In [20]:
print(np.flip(state, 1))

[[0 2 1]
 [1 0 2]
 [2 2 2]]


## Possibility #6

Flip board across central horizontal line.

In [13]:
print(np.flip(state, 0))

[[2 2 2]
 [2 0 1]
 [1 2 0]]


## Possibility #7

Rotate 270 degrees clock-wise.

In [21]:
print(np.flip(np.transpose(state), 0))

[[0 1 2]
 [2 0 2]
 [1 2 2]]


## Superfluous Manipulations

Same as Possibliity #0

In [22]:
print(np.transpose(np.flip(np.flip(np.transpose(state), 0), 0)))

[[1 2 0]
 [2 0 1]
 [2 2 2]]
